// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeRMGW01_j3ivRGppZBHYhZjWQ1pXQS5E',
    appId: '1:317158506100:web:ec2517d94ae1c2c7cf1b21',
    messagingSenderId: '317158506100',
    projectId: 'lingo-fb923',
    authDomain: 'lingo-fb923.firebaseapp.com',
    storageBucket: 'lingo-fb923.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRdQ_DNZXnrEXzOfZClRGmPQqrqXzmEQM',
    appId: '1:317158506100:android:97444e6783546612cf1b21',
    messagingSenderId: '317158506100',
    projectId: 'lingo-fb923',
    storageBucket: 'lingo-fb923.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLCAffeqW49lo5FbJYg2RJbDOQucTwICQ',
    appId: '1:317158506100:ios:b5b553ae72a1b9b8cf1b21',
    messagingSenderId: '317158506100',
    projectId: 'lingo-fb923',
    storageBucket: 'lingo-fb923.firebasestorage.app',
    androidClientId: '317158506100-6r8lvo6fmhgql3fkk9n2lmhbq3oendsg.apps.googleusercontent.com',
    iosClientId: '317158506100-tsjgn2ph7n6ek3epncdl0id7d4358ft0.apps.googleusercontent.com',
    iosBundleId: 'com.example.duolingoClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLCAffeqW49lo5FbJYg2RJbDOQucTwICQ',
    appId: '1:317158506100:ios:b5b553ae72a1b9b8cf1b21',
    messagingSenderId: '317158506100',
    projectId: 'lingo-fb923',
    storageBucket: 'lingo-fb923.firebasestorage.app',
    androidClientId: '317158506100-6r8lvo6fmhgql3fkk9n2lmhbq3oendsg.apps.googleusercontent.com',
    iosClientId: '317158506100-tsjgn2ph7n6ek3epncdl0id7d4358ft0.apps.googleusercontent.com',
    iosBundleId: 'com.example.duolingoClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeRMGW01_j3ivRGppZBHYhZjWQ1pXQS5E',
    appId: '1:317158506100:web:10c43b6084d5ee5dcf1b21',
    messagingSenderId: '317158506100',
    projectId: 'lingo-fb923',
    authDomain: 'lingo-fb923.firebaseapp.com',
    storageBucket: 'lingo-fb923.firebasestorage.app',
  );
}
